#!/bin/bash
# fix_book_snapshots_pk.sh - Rebuild book_snapshots table dengan PK yang benar
# 
# KONTEKS: De-dup historis pakai CREATE TABLE AS SELECT merusak kolom PRIMARY KEY,
# menyebabkan id berhenti jadi INTEGER PRIMARY KEY AUTOINCREMENT dan baris baru 
# dapat id=NULL. Script ini rebuild tabel dengan skema yang benar.
#
# SAFETY: Bekerja di file BACKUP, bukan DB live (hindari 'database is locked')
# 
# USAGE:
#   cd ~/cepiokta
#   bash scripts/fix_book_snapshots_pk.sh

set -euo pipefail

DB_LIVE="$HOME/cepiokta/btcbot.db"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DB_BACKUP="$HOME/cepiokta/btcbot.backup.${TIMESTAMP}.db"

echo "=== FIX BOOK_SNAPSHOTS PRIMARY KEY ==="
echo "Timestamp: $(date)"
echo ""

# STEP 1: Backup DB live
echo "[1/6] Creating backup..."
if [ ! -f "$DB_LIVE" ]; then
    echo "ERROR: $DB_LIVE not found!"
    exit 1
fi

cp "$DB_LIVE" "$DB_BACKUP"
echo "✓ Backup created: $DB_BACKUP"
echo ""

# STEP 2: Pre-check - Count distinct rounds BEFORE
echo "[2/6] Pre-check: Counting distinct rounds BEFORE..."
ROUNDS_BEFORE=$(sqlite3 "$DB_BACKUP" "SELECT COUNT(DISTINCT round_no) FROM book_snapshots;")
TOTAL_BEFORE=$(sqlite3 "$DB_BACKUP" "SELECT COUNT(*) FROM book_snapshots;")
NULL_IDS=$(sqlite3 "$DB_BACKUP" "SELECT COUNT(*) FROM book_snapshots WHERE id IS NULL;")

echo "  Total rows BEFORE:          $TOTAL_BEFORE"
echo "  Distinct round_no BEFORE:   $ROUNDS_BEFORE"
echo "  Rows with id=NULL:          $NULL_IDS"
echo ""

# STEP 3: Show current (broken) schema
echo "[3/6] Current (broken) schema:"
sqlite3 "$DB_BACKUP" "SELECT sql FROM sqlite_master WHERE name='book_snapshots';" | head -20
echo ""

# STEP 4: Rebuild table with correct PRIMARY KEY
echo "[4/6] Rebuilding table with correct PRIMARY KEY..."
sqlite3 "$DB_BACKUP" <<'EOF'
BEGIN TRANSACTION;

-- Create new table with CORRECT schema
CREATE TABLE book_snapshots_new (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    round_no INTEGER,
    token_id TEXT,
    ts TEXT,
    best_bid TEXT,
    best_ask TEXT,
    bid_depth TEXT,
    ask_depth TEXT,
    gap INTEGER NOT NULL DEFAULT 0,
    raw TEXT,
    mode TEXT
);

-- Copy ALL data (id will be regenerated by AUTOINCREMENT)
-- DO NOT copy id column - let SQLite auto-generate new sequential ids
INSERT INTO book_snapshots_new (
    round_no, token_id, ts, best_bid, best_ask, bid_depth,
    ask_depth, gap, raw, mode
)
SELECT 
    round_no, token_id, ts, best_bid, best_ask, bid_depth,
    ask_depth, gap, raw, mode
FROM book_snapshots
ORDER BY 
    COALESCE(id, 999999999999999),  -- NULL ids go last
    round_no,                        -- then by round_no
    ts;                              -- then by timestamp

-- Drop old table
DROP TABLE book_snapshots;

-- Rename new table
ALTER TABLE book_snapshots_new RENAME TO book_snapshots;

-- Recreate index
CREATE INDEX idx_book_snapshots_round_ts ON book_snapshots(round_no, ts);

COMMIT;
EOF

echo "✓ Table rebuilt with correct schema"
echo ""

# STEP 5: Post-check - Count distinct rounds AFTER
echo "[5/6] Post-check: Counting distinct rounds AFTER..."
ROUNDS_AFTER=$(sqlite3 "$DB_BACKUP" "SELECT COUNT(DISTINCT round_no) FROM book_snapshots;")
TOTAL_AFTER=$(sqlite3 "$DB_BACKUP" "SELECT COUNT(*) FROM book_snapshots;")
NULL_IDS_AFTER=$(sqlite3 "$DB_BACKUP" "SELECT COUNT(*) FROM book_snapshots WHERE id IS NULL;")
MIN_ID=$(sqlite3 "$DB_BACKUP" "SELECT MIN(id) FROM book_snapshots;")
MAX_ID=$(sqlite3 "$DB_BACKUP" "SELECT MAX(id) FROM book_snapshots;")

echo "  Total rows AFTER:           $TOTAL_AFTER"
echo "  Distinct round_no AFTER:    $ROUNDS_AFTER"
echo "  Rows with id=NULL:          $NULL_IDS_AFTER"
echo "  MIN(id):                    $MIN_ID"
echo "  MAX(id):                    $MAX_ID"
echo ""

# STEP 6: Verify new schema
echo "[6/6] New (fixed) schema:"
sqlite3 "$DB_BACKUP" "SELECT sql FROM sqlite_master WHERE name='book_snapshots';"
echo ""

# STEP 7: CRITICAL VALIDATION
echo "=== VALIDATION ==="
if [ "$ROUNDS_BEFORE" -ne "$ROUNDS_AFTER" ]; then
    echo "❌ FAILED: Round count mismatch!"
    echo "   BEFORE: $ROUNDS_BEFORE rounds"
    echo "   AFTER:  $ROUNDS_AFTER rounds"
    echo "   DIFF:   $((ROUNDS_AFTER - ROUNDS_BEFORE))"
    echo ""
    echo "   DO NOT USE THIS BACKUP!"
    exit 1
fi

if [ "$TOTAL_BEFORE" -ne "$TOTAL_AFTER" ]; then
    echo "⚠️  WARNING: Row count changed"
    echo "   BEFORE: $TOTAL_BEFORE rows"
    echo "   AFTER:  $TOTAL_AFTER rows"
    echo "   DIFF:   $((TOTAL_AFTER - TOTAL_BEFORE))"
    echo ""
fi

if [ "$NULL_IDS_AFTER" -ne 0 ]; then
    echo "❌ FAILED: Still have NULL ids!"
    echo "   Rows with id=NULL: $NULL_IDS_AFTER"
    echo ""
    echo "   DO NOT USE THIS BACKUP!"
    exit 1
fi

echo "✅ VALIDATION PASSED"
echo "   ✓ Round count preserved: $ROUNDS_BEFORE rounds"
echo "   ✓ No NULL ids: $NULL_IDS_AFTER"
echo "   ✓ PRIMARY KEY AUTOINCREMENT: working"
echo ""

# STEP 8: Instructions
echo "=== NEXT STEPS ==="
echo ""
echo "1. VERIFY backup is good:"
echo "   sqlite3 $DB_BACKUP 'SELECT COUNT(DISTINCT round_no) FROM book_snapshots;'"
echo ""
echo "2. STOP bot (in tmux 'soak' session):"
echo "   tmux attach -t soak"
echo "   Ctrl+C (stop bot)"
echo "   exit"
echo ""
echo "3. REPLACE live DB with fixed backup:"
echo "   mv $DB_LIVE ${DB_LIVE}.broken.${TIMESTAMP}"
echo "   cp $DB_BACKUP $DB_LIVE"
echo ""
echo "4. RESTART bot:"
echo "   cd ~/cepiokta"
echo "   tmux new -s soak"
echo "   uv run python -m btcbot.app.cli"
echo ""
echo "5. VERIFY new rows get valid ids:"
echo "   # Wait 5 minutes for bot to write some data"
echo "   sqlite3 $DB_LIVE 'SELECT id, round_no, token_id, ts FROM book_snapshots ORDER BY id DESC LIMIT 10;'"
echo "   # All ids should be NOT NULL and sequential"
echo ""

echo "=== DONE ==="
echo "Fixed backup: $DB_BACKUP"
